add more tempating posibility for Service managment.
flipt-io/helm-charts pull request #49
Opened 2023-03-09 08:53 UTC by tomaszmichalowski

Solves Issue #47

2023-03-09 09:52 UTC, GeorgeMac requested changes
Thanks again for the contribution here! Just one small request for backwards compatibility.

2023-03-09 09:52 UTC, GeorgeMac commented on charts/flipt/templates/service.yaml
> +{{- if .Values.service.enabled }}
As this (`service.enabled`) is a new property, could we perhaps make it so that it renders the service if this value is not defined. For  backwards compatibility.

As in:

```suggestion
{{- if (or (empty .Values.service.enabled) .Values.service.enabled))}}
```

2023-03-09 11:45 UTC, GeorgeMac requested changes
I made a typo which is breaking it. My bad.

2023-03-09 11:45 UTC, GeorgeMac commented on charts/flipt/templates/service.yaml
> +{{- if (or (empty .Values.service.enabled) .Values.service.enabled))}}
```suggestion
{{- if (or (empty .Values.service.enabled) .Values.service.enabled)}}
```
Was a mistake in the github suggestion I made. Apologies.

2023-03-09 17:19 UTC, GeorgeMac commented on charts/flipt/templates/service.yaml
> +{{- if (or (empty .Values.service.enabled) .Values.service.enabled))}}
@tomaszmichalowski just a heads up. One this fix is applied I think it is ready to merge (given tests pass).
I left it here for you to do the honours. Just to sanity check me.

2023-03-10 11:13 UTC, tomaszmichalowski commented
Still need to work on this if statement

```The output of this statement depends on the value of .Values.service.enabled.

If .Values.service.enabled is true, then the or function will short-circuit and return true, and the if statement will evaluate to true.

If .Values.service.enabled is false, then the or function will evaluate (empty .Values.service.enabled) which will return true because .Values.service.enabled is empty (i.e., it does not exist or its value is an empty string). Therefore, the or function will return true, and the if statement will evaluate to true.

If .Values.service.enabled is not set or is set to a non-boolean value (e.g., a string), then (empty .Values.service.enabled) will also return true because it checks for the existence of the value. Therefore, the or function will return true, and the if statement will evaluate to true.

So, in summary, the if statement will evaluate to true if .Values.service.enabled does not exist, is an empty string, or is set to true.```

2023-03-10 12:02 UTC, tomaszmichalowski commented
now works:
service.enabled = true -> service generated
service.enabled = false -> service disabled
service.enabled does not exist -> service generated

2023-03-10 13:27 UTC, merged

2023-03-10 13:28 UTC, GeorgeMac commented
Thanks @tomaszmichalowski !