add default helm Ingress template
flipt-io/helm-charts pull request #50
Opened 2023-03-09 09:09 UTC by tomaszmichalowski

Add default Ingress from helm default template.
Solves #48

2023-03-09 09:48 UTC, GeorgeMac requested changes
Thanks for the contribution (and associated issue)! This is indeed a gap in the templates.

I think you just need to bump the version. Maybe a patch will suffice, since this is a feature in the values which is not being acknowledged.
Also, am I right in thinking the changes to service.yaml in this PR is a duplicate of your other PR?

2023-03-09 09:48 UTC, GeorgeMac commented on charts/flipt/templates/service.yaml
> +{{- if .Values.service.enabled }}
I think this change is in your other PR, is that right?

2023-03-09 10:53 UTC, tomaszmichalowski commented on charts/flipt/templates/service.yaml
> +{{- if .Values.service.enabled }}
I've removed this commit from that PR.

2023-03-13 09:35 UTC, GeorgeMac commented
Hey @tomaszmichalowski I think you just need to merge in master or rebase 👍 
I think the chart version is conflicting since we merged in the other PR.

2023-03-13 10:20 UTC, tomaszmichalowski commented
Main branch has beed merged to PR

2023-03-13 13:41 UTC, GeorgeMac approved these changes

2023-03-13 13:41 UTC, merged

2023-03-13 13:41 UTC, GeorgeMac commented
Thanks @tomaszmichalowski 🙏